create table parking_lot_order (
    id bigint generated by default as identity,
    car_id varchar(255), create_time timestamp,
    end_time timestamp,
    order_status boolean default 0,
    parking_lot_id bigint, primary key (id));
alter table parking_lot_order
    add constraint parking_lot_id_fk
    foreign key (parking_lot_id) references parking_lot;